# Generated by Django 3.2.8 on 2021-11-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('userid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('passwd', models.CharField(blank=True, max_length=20, null=True)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'members',
                'managed': False,
            },
        ),
    ]
