# Generated by Django 3.2.8 on 2021-12-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('userid', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'graph',
                'managed': False,
            },
        ),
    ]
